# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-04 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobilename', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GridLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('input_type', models.CharField(max_length=50)),
                ('properties', models.CharField(max_length=200)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hc.Control')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('size_x', models.IntegerField()),
                ('size_y', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('control_id', models.IntegerField()),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hc.GridLayout')),
            ],
        ),
    ]
